name: Print Working Directory

on:
  push:
    branches:
      - main

jobs:
  print-working-directory:
    name: Print Working Directory
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print working directory
        run: echo "Current working directory: $PWD"
